from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol

import pandas as pd

from unisa_air_twin.config import Settings


class OperationalStore(Protocol):
    def backend_name(self) -> str: ...

    def database_path(self, settings: Settings) -> str | Path: ...

    def connect_db(self, settings: Settings) -> Any: ...

    def ensure_schema(self, settings: Settings) -> None: ...

    def replace_sensors(self, settings: Settings, sensors: pd.DataFrame) -> None: ...

    def replace_observations(self, settings: Settings, observations: pd.DataFrame) -> None: ...

    def upsert_observations(self, settings: Settings, observations: pd.DataFrame) -> int: ...

    def append_raw_messages(self, settings: Settings, rows: list[dict[str, Any]]) -> int: ...

    def replace_snapshots(self, settings: Settings, snapshots: pd.DataFrame) -> None: ...

    def read_sensors(self, settings: Settings) -> pd.DataFrame: ...

    def read_observations(self, settings: Settings) -> pd.DataFrame: ...

    def read_snapshots(self, settings: Settings) -> pd.DataFrame: ...

    def read_snapshot_timestamps(self, settings: Settings, pollutant: str) -> list[str]: ...

    def read_snapshot(self, settings: Settings, pollutant: str, timestamp: str | pd.Timestamp) -> pd.DataFrame: ...

    def read_sensor_snapshot(self, settings: Settings, sensor_id: str, timestamp: str | pd.Timestamp) -> pd.DataFrame: ...

    def read_recent_observations(self, settings: Settings, since_timestamp: str | None = None) -> pd.DataFrame: ...

    def read_sensor_observations(self, settings: Settings, sensor_id: str) -> pd.DataFrame: ...

    def read_sensor_timeseries(self, settings: Settings, pollutant: str, sensor_name: str) -> pd.DataFrame: ...

    def read_raw_messages(self, settings: Settings) -> pd.DataFrame: ...

    def read_raw_message_count(self, settings: Settings) -> int: ...

    def upsert_job_run(self, settings: Settings, job: dict[str, Any]) -> None: ...

    def read_job_run(self, settings: Settings, job_id: str) -> dict[str, Any] | None: ...

    def read_job_runs(self, settings: Settings, limit: int = 20) -> list[dict[str, Any]]: ...

    def write_ingestion_run(self, settings: Settings, metadata: dict[str, Any], status: str = "completed") -> None: ...

    def write_metadata(self, settings: Settings, key: str, value: Any) -> None: ...

    def read_metadata(self, settings: Settings) -> dict[str, Any]: ...

    def append_operational_event(
        self,
        settings: Settings,
        event_type: str,
        payload: dict[str, Any],
        *,
        aggregate_type: str | None = None,
        aggregate_id: str | None = None,
        occurred_at: str | None = None,
    ) -> int: ...

    def read_operational_events(
        self,
        settings: Settings,
        *,
        after_event_id: int = 0,
        limit: int = 100,
    ) -> list[dict[str, Any]]: ...

    def read_latest_event_id(self, settings: Settings) -> int: ...

    def upsert_projection_failure(self, settings: Settings, failure: dict[str, Any]) -> None: ...

    def read_projection_failure(self, settings: Settings, event_id: int) -> dict[str, Any] | None: ...

    def delete_projection_failure(self, settings: Settings, event_id: int) -> None: ...

    def read_projection_failures(
        self,
        settings: Settings,
        *,
        status: str | None = None,
        limit: int = 100,
    ) -> list[dict[str, Any]]: ...

    def read_projection_failure_summary(self, settings: Settings) -> dict[str, Any]: ...
